modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="createcoolingfan"
version="${mod_version}"
displayName="Create Cooling Fan"
authors="Chemiofitor"
description='''
The encased fan that can cool casting.
'''
[[dependencies.createcoolingfan]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.createcoolingfan]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.createcoolingfan]]
modId="create"
mandatory=true
versionRange="[6.0.6,)"
ordering="NONE"
side="BOTH"
[[dependencies.createcoolingfan]]
modId="tconstruct"
mandatory=true
versionRange="[3.10.1.0,)"
ordering="NONE"
side="BOTH"